despensa/Models/Factura.cs
using System;
using System.Collections.Generic;

namespace despensa.Models
{
    public partial class Factura
    {
        public int CodFactura { get; set; }
        public DateTime? Fecha { get; set; }
        public int? CodEmpleado { get; set; }
        public int? CodCliente { get; set; }

        public virtual Usuario CodClienteNavigation { get; set; }
        public virtual Usuario CodEmpleadoNavigation { get; set; }
    }
}

despensa/Models/PredidoFactura.cs
using System;
using System.Collections.Generic;

namespace despensa.Models
{
    public partial class PredidoFactura
    {
        public PredidoFactura()
        {
            DetalleFactura = new HashSet<DetalleFactura>();
        }

        public int CodFactura { get; set; }
        public DateTime? FecEmision { get; set; }
        public decimal? TotalVendido { get; set; }
        public decimal? TotalCosto { get; set; }
        public int? CodEmpleado { get; set; }
        public int? CodCliente { get; set; }
        public int? CodEstado { get; set; }
        public string Direccion_entrega { get; set; }

        public virtual Usuario CodClienteNavigation { get; set; }
        public virtual Usuario CodEmpleadoNavigation { get; set; }
        public virtual EstadoPedido CodEstadoNavigation { get; set; }
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
    }
}

despensa/Controllers/PredidoFacturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using despensa.Models;
using despensa.Helpers;
using System.Security.Claims;
using MySql.Data.MySqlClient.Memcached;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;

namespace despensa.Controllers
{
    public class PredidoFacturasController : Controller
    {
        private readonly despensa1Context _context;

        public PredidoFacturasController(despensa1Context context)
        {
            _context = context;
        }
        [Authorize(Roles = "3,2")]
        // GET: PredidoFacturas
        public IActionResult PedidosPendientes()
        {
            var entradas = (from m in _context.PredidoFactura.Include(p => p.CodClienteNavigation).Include(p => p.CodEmpleadoNavigation).Include(p => p.CodEstadoNavigation)
                            where m.CodEstado == 1
                            orderby m.FecEmision ascending
                            select m).ToList();
            return View(entradas);
        }
        [Authorize(Roles = "3,2")]
        public IActionResult TodosPedidos(int? page, string Nombre, string FecFinal, string FecInici)
        {
            var pageNumber = page ?? 1;
            var entradas = (from m in _context.PredidoFactura.Include(p => p.CodClienteNavigation).Include(p => p.CodEmpleadoNavigation).Include(p => p.CodEstadoNavigation)
                            orderby m.FecEmision ascending
                            select m).ToList();
            Console.WriteLine("Filtro de predido factura: nombre: '" + Nombre + "' fecini: '" + FecFinal + "' fecfin: '" + FecInici + "'");

            if (Nombre != "" && Nombre != null) { ViewBag.nombre = Nombre; entradas = entradas.Where(a => a.CodClienteNavigation.PrimerNombre.ToLower().Contains(Nombre.ToLower()) || a.CodClienteNavigation.PrimerApellido.ToLower().Contains(Nombre.ToLower())).ToList(); }
            if (FecInici != "" && FecFinal != "" && FecInici != null && FecFinal != null) {
                try
                {
                    DateTime fecini = DateTime.ParseExact(FecInici, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
                    DateTime fecfin = DateTime.ParseExact(FecFinal, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
                    entradas = entradas.Where(a => a.FecEmision >= fecini && a.FecEmision <= fecfin).ToList();
                    ViewBag.fech1 = FecInici;
                    ViewBag.fech2 = FecFinal;
                }
                catch (Exception ex) { Console.WriteLine(ex); }
            }
            var unaPagina = entradas.ToPagedList(pageNumber, 18);
            return View(unaPagina);
        }

        // GET: PredidoFacturas/Details/5
        [Authorize(Roles = "3,2,1")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var predidoFactura = await _context.PredidoFactura
                .Include(p => p.CodClienteNavigation)
                .Include(p => p.CodEmpleadoNavigation)
                .Include(p => p.CodEstadoNavigation)
                .FirstOrDefaultAsync(m => m.CodFactura == id);
            var detallefactura = (from m in _context.DetalleFactura.Include(p => p.CodProductoNavigation)
                                  where m.CodFactura == id
                                  select m).ToList();
            if (predidoFactura == null)
            {
                return NotFound();
            }
            ViewBag.cantidad = detallefactura.Count;
            ViewBag.detalleFactura = detallefactura;
            return View(predidoFactura);
        }

        // GET: PredidoFacturas/Create
        [Authorize(Roles = "3,2,1")]
        public async Task<IActionResult> Create()
        {
            ClaimsPrincipal currentUser = this.User;
            var identity = (ClaimsIdentity)currentUser.Identity;
            int id= Int32.Parse(identity.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value);
            var usuario = await _context.Usuario
                .Include(u => u.CodEstadoNavigation)
                .Include(u => u.CodGeneoNavigation)
                .Include(u => u.CodRolNavigation)
                .FirstOrDefaultAsync(m => m.CodUsuario == id);
            ViewData["CodCliente"] = new SelectList(_context.Usuario, "CodUsuario", "CodUsuario");
            ViewData["CodEmpleado"] = new SelectList(_context.Usuario, "CodUsuario", "CodUsuario");
            ViewData["CodEstado"] = new SelectList(_context.EstadoPedido, "CodEstado", "CodEstado");
                return View(usuario);
        }

        [Authorize(Roles = "3,2,1")]
        public async Task<IActionResult> Factura(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var factura = await _context.PredidoFactura
                .Include(f => f.CodClienteNavigation)
                .Include(f => f.CodEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.CodFactura == id);
            var aux = _context.Usuario.Where(a => a.CodUsuario == factura.CodEmpleado);

            var detallefactura = (from m in _context.DetalleFactura.Include(p => p.CodProductoNavigation)
                                  where m.CodFactura == id
                                  select m).ToList();
            if (factura == null)
            {
                return NotFound();
            }

            ViewBag.cantidad = detallefactura.Count;
            ViewBag.detalleFactura = detallefactura;
            ViewBag.factura = factura;
            ViewBag.empleado = factura.CodEmpleadoNavigation.PrimerNombre+" "+factura.CodEmpleadoNavigation.SegundoNombre+" "+factura.CodEmpleadoNavigation.PrimerApellido+" "+factura.CodEmpleadoNavigation.SegundoApellido;
            return View();

        }

        // POST: PredidoFacturas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "3,2,1")]
        public async Task<IActionResult> Create([Bind("CodFactura,Direccion_entrega,FecEmision,TotalVendido,TotalCosto,CodEmpleado,CodCliente,CodEstado")] PredidoFactura predidoFactura)
        {
            ClaimsPrincipal currentUser = this.User;
            var identity = (ClaimsIdentity)currentUser.Identity;
            decimal? totalxproducto = 0;
            decimal? totalxproducto1 = 0;
            decimal? totalventa = 0;
            decimal? totalcosto = 0;
            List<DetalleFactura> lista = new List<DetalleFactura>();
            try
            {
                var entradas = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                if (entradas==null)
                {
                    ViewBag.ErrorCarrito = 3;
                    return View();
                }
                foreach (var item in entradas)
                {
                    if (item.Quantity == 0)
                    {
                        ViewBag.ErrorCarrito = 4;
                        return View();
                    }
                    lista.Add(new DetalleFactura { Precio = item.Product.PrecioVenta, Costo = item.Product.PrecioCosto, CodProducto = item.Product.CodProducto, Cantidad = item.Quantity });
                    totalxproducto = item.Product.PrecioVenta * item.Quantity;
                    totalxproducto1 = item.Product.PrecioCosto * item.Quantity;
                    totalventa = totalventa + totalxproducto;
                    totalcosto = totalcosto + totalxproducto1;
                    var producto = await _context.Producto.FindAsync(item.Product.CodProducto);
                    if (producto.Cantidad < item.Quantity)
                    {
                        ViewBag.Inexistencia = producto;
                        ViewBag.ErrorCarrito = 2;
                        return View();
                    }
                }
                if (totalventa < 50)
                {
                    ViewBag.ErrorCarrito = 1;
                    return View();
                }
                else {
                    foreach (var item in entradas)
                    {
                        var producto = await _context.Producto.FindAsync(item.Product.CodProducto);
                        producto.Cantidad = producto.Cantidad - item.Quantity;
                        _context.Update(producto);
                        await _context.SaveChangesAsync();
                    }
                }
            }
            catch
            {
                ViewBag.ErrorCarrito = 3;
                return View();
            }


            if (ModelState.IsValid)
            {
                string fecha = DateTime.Now.ToString("dd/MM/yyyy");
                predidoFactura.FecEmision= DateTime.Now;
                predidoFactura.TotalVendido = totalventa;
                predidoFactura.TotalCosto = totalcosto;
                predidoFactura.CodCliente = Int32.Parse(identity.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value);
                predidoFactura.CodEstado=1;
                predidoFactura.DetalleFactura = lista;
                _context.Add(predidoFactura);
                await _context.SaveChangesAsync();
                limpiarCarrito();
                return RedirectToAction("Index", "Categorias", new { a = "PedidoSatisfactorio", b=predidoFactura.TotalVendido, c= fecha });
            }
            ViewBag.Pedidofactura = "entre aqui";
            ViewData["CodCliente"] = new SelectList(_context.Usuario, "CodUsuario", "CodUsuario", predidoFactura.CodCliente);

despensa/Views/PredidoFacturas/Create.cshtml
@model despensa.Models.Usuario

@{
    ViewData["Title"] = "Pedido";
    Layout = "~/Views/Shared/vistasincarro.cshtml";
}
<link rel="stylesheet" href="~/css/login.css">
<div class="privacy">
    <div class="container">
        <!-- tittle heading -->
        <h3 class="tittle-w3l">
            Mi Pedido


            <span class="heading-style">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </h3>
        @if (@ViewBag.ErrorCarrito == 1)
        {
            <div class="alert alert-danger text-center">
                <strong>Su Compra Debe Ser Mayor A Q50</strong>
            </div>

        }
        else if (@ViewBag.ErrorCarrito == 2)
        {
            <div class="alert alert-danger text-center">
                <strong>En Estos Momentos No Contamos Las Unidades Suficientes De:</strong>
                <strong>@ViewBag.Inexistencia.Nombre , Quedan @ViewBag.Inexistencia.Cantidad Unidades</strong>
            </div>

        }
        else if (@ViewBag.ErrorCarrito == 3)
        {
            <div class="alert alert-danger text-center">
                <strong>El Carrito Se Encuentra Vacio</strong>
            </div>
        }
        else if (@ViewBag.ErrorCarrito == 4)
        {
            <div class="alert alert-danger text-center">
                <strong>No Puede Ir Una Cantidad En 0</strong>
            </div>
        }
        <!-- //tittle heading -->
        <div class="checkout-right">
            <h4>
                Usted ha añadido:
                <span id="cantidad_producntos">0 Productos @ViewBag.ErrorCarrito</span>
            </h4>
            <div class="table-responsive">
                <table id="lstProductos" class="timetable_sub">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Remover</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4">Total</td>
                            <td class="total"></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div class="checkout-left">
            <div class="address_form_agile">
                <h4>Sus Datos Personales</h4>

                <div class="fila-arriba">
                    <div class="contenedor-input">
                        <label class="active highlight">
                            Primer Nombre <span class="req">*</span>
                        </label>
                        <div class="divinput" style="width:100%;">  @Html.DisplayFor(model => model.PrimerNombre)</div>
                    </div>

                    <div class="contenedor-input">
                        <label class="active highlight">
                            Segundo Nombre <span class="req">*</span>
                        </label>
                        <div class="divinput" style="width:100%;">  @Html.DisplayFor(model => model.SegundoNombre)</div>
                    </div>
                </div>
                <div class="fila-arriba">
                    <div class="contenedor-input">
                        <label class="active highlight">
                            Primer Apellido <span class="req">*</span>
                        </label>
                        <div class="divinput" style="width:100%;">  @Html.DisplayFor(model => model.PrimerApellido)</div>
                    </div>

                    <div class="contenedor-input">
                        <label class="active highlight">
                            Segundo Apellido <span class="req">*</span>
                        </label>
                        <div class="divinput" style="width:100%;">  @Html.DisplayFor(model => model.SegundoApellido)</div>
                    </div>
                </div>
                <div class="fila-arriba">
                    <div class="contenedor-input">
                        <label class="active highlight">
                            CUI <span class="req">*</span>
                        </label>
                        <div class="divinput" style="width:100%;">  @Html.DisplayFor(model => model.Cui)</div>
                    </div>

                    <div class="contenedor-input">
                        <label class="active highlight">
                            NIT <span class="req">*</span>
                        </label>
                        <div class="divinput" style="width:100%;">  @Html.DisplayFor(model => model.Nit)</div>
                    </div>
                </div>


                <form asp-action="Create">
                    <h4>En esta direcciones desea el pedido?</h4>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="contenedor-input">
                        <label class="active highlight">
                            Direccion <span class="req">*</span>
                        </label>
                        <input name="Direccion_entrega" type="text" value="@Html.DisplayFor(model => model.Direccion)" autocomplete="off" readonly onfocus="this.removeAttribute('readonly');" required>
                    </div>
                    <div class="text-center">
                        <input value="Guardar" type="submit" style="width:150px;" class="botones validar redondear">
                        <a asp-controller="Home" asp-action="Index" class="botones danger redondear">Regresar</a>
                    </div>
                </form>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

despensa/Views/PredidoFacturas/Factura.cshtml
@{
    ViewData["Title"] = "Factura";
    Layout = "~/Views/Shared/facturaLayout.cshtml";
}
<div class="control-bar">
    <div class="container">
        <div class="row">
            <div class="col-2-4">
                <div class="slogan">Facturación </div>

                <label for="config_tax">
                    IVA:
                    <input type="checkbox" id="config_tax" checked />
                </label>
                <label for="config_tax_rate" class="taxrelated">
                    Tasa:
                    <input type="text" id="config_tax_rate" value="12" hidden />%
                </label>
                <label for="config_note">
                    Nota:
                    <input type="checkbox" id="config_note" />
                </label>
                <label for="config_note">
                    <a asp-controller="Usuarios" asp-action="Details" asp-route-Austoscroll="pedidos">Mis Pedidos</a>
                </label>
                <label for="config_note">
                    @if (@User.IsInRole("3") || User.IsInRole("2"))
                    {
                        <a asp-controller="PredidoFacturas" asp-action="TodosPedidos">Todods los pedidos</a>
                    }
                </label>

            </div>
            <div class="col-4 text-right">
                <a href="javascript:window.print()">Imprimir</a>
            </div><!--.col-->
        </div><!--.row-->
    </div><!--.container-->
</div><!--.control-bar-->




<div class="row section">

    <div class="col-2">
        <h1 contenteditable>    </h1>
    </div><!--.col-->

    <div class="col-2 text-right details">
        <p contenteditable>
            Fecha: <input type="date"  value="@ViewBag.factura.FecEmision"/><br>
            Factura #: <input type="text" value="@ViewBag.factura.CodFactura" /><br>
        </p>
    </div><!--.col-->



    <div class="col-2">


        <p contenteditable class="client">
            <strong>Facturar a</strong><br>
            Nombre: @ViewBag.factura.CodClienteNavigation.PrimerNombre <br>
            Apellido: @ViewBag.factura.CodClienteNavigation.SegundoNombre<br>
            Direccion: @ViewBag.factura.CodClienteNavigation.Direccion<br>
            Telefoo: @ViewBag.factura.CodClienteNavigation.Telefono
        </p>
    </div><!--.col-->


    <div class="col-2">


        <p contenteditable class="client">
            <strong></strong><br>
            DPI: @ViewBag.factura.CodClienteNavigation.Cui<br>
            NIT: @ViewBag.factura.CodClienteNavigation.Nit<br>
            Correo: @ViewBag.factura.CodClienteNavigation.CorreoElectronico<br>
        </p>
    </div><!--.col-->



</div><!--.row-->

<div class="row section" style="margin-top:-1rem">
    <div class="col-1">
        <table style='width:100%'>
            <thead contenteditable>
                <tr class="invoice_detail">
                    <th width="70%" style="text-align:center">Empleado</th>
                    <th width="30%">Términos y condiciones</th>
                </tr>
            </thead>
            <tbody contenteditable>
                <tr class="invoice_detail">
                    <td width="70%" style="text-align:center">@ViewBag.empleado</td>
                    <td width="30%">Pago A Contra Enctrega</td>
                </tr>
            </tbody>
        </table>
    </div>

</div><!--.row-->

<div class="invoicelist-body">
    <table>
        <thead contenteditable>
            <tr>
                <th width="5%">Código</th>
                <th width="60%">Descripción</th>

                <th width="10%">Cant.</th>
                <th width="15%">Precio</th>
                <th class="taxrelated">IVA</th>
                <th width="10%">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.detalleFactura)
            {
                <tr>
                    <td width='5%'><span contenteditable>@item.CodFactura</span></td>
                    <td width='60%'><span contenteditable>@item.CodProductoNavigation.Nombre @item.CodProductoNavigation.Peso</span></td>
                    <td class="amount"><input type="text" value="@item.Cantidad" /></td>
                    <td class="rate"><input type="text" value="@item.CodProductoNavigation.PrecioVenta" /></td>
                    <td class="tax taxrelated"></td>
                    <td class="sum">@(item.CodProductoNavigation.PrecioVenta * item.Cantidad)</td>
                </tr>
            }


        </tbody>
    </table>
</div><!--.invoice-body-->

<div class="invoicelist-footer">
    <table contenteditable>
        <tr class="taxrelated">
            <td>IVA:</td>
            <td id="total_tax"></td>
        </tr>
        <tr>
            <td><strong>Total:</strong></td>
            <td>Q.@ViewBag.factura.TotalVendido</td>
        </tr>
    </table>
</div>

<div class="note" contenteditable>
    <h2>Nota:</h2>
</div><!--.note-->

despensa/Views/PredidoFacturas/TodosPedidos.cshtml
@model IEnumerable<despensa.Models.PredidoFactura>
@using X.PagedList
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Pedido";
}


<link rel="stylesheet" href="~/css/login.css">
<link rel="stylesheet" href="~/css/pedidos.css">
<link rel="stylesheet" href="~/css/pikaday.css">
<div class="container">
    <!-- tittle heading -->
    <h3 class="tittle-w3l">
        Todos los Pedidos
        <span class="heading-style">
            <i></i>
            <i></i>
            <i></i>
        </span>
    </h3>
</div>
<div class="container" style="margin-bottom: 10px;">
    <form asp-controller="PredidoFacturas" asp-action="TodosPedidos" method="get">
        <div class="pikarange">
            <div class="col-6 col-md-3"><input id="FecInici" name="FecInici" type="text" class="pikarange-start" placeholder="Fecha Incial" /></div>
            <div class="col-6 col-md-3"><input id="FecFinal" name="FecFinal" type="text" class="pikarange-end" placeholder="Fecha Final" /></div>
        </div>
        <div class="col-6 col-md-3">
            <input id="Nombre" name="Nombre" type="text" placeholder="Nombre Cliente" />
        </div>
        <input type="submit" class="botones success redondear" value="Filtrar" style="max-width: 10%; max-height: 50px; padding: 0px;">
    </form>
</div>
<div class="contenedor-formularios" style="margin:0 auto; max-width: 100%; padding-top: 0px;">
    <div class="contenido-tab">
        <div id="iniciar-sesion">
            <div>
                @foreach (var item in Model)
                {
                    <div class="col-md-2 product-men" style="margin-top: 0px; margin-bottom: 30px;">
                        <div class="men-pro-item simpleCart_shelfItem">
                            <div class="item-info-product ">
                                @if (item.CodEstado == 1)
                                {
                                    <a asp-action="Edit" asp-route-id="@item.CodFactura">
                                        <div class="plan basic" onclick="void(0);" style="width: 100%;">
                                            <div class="title"> @Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre) @Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerApellido)</div>
                                            <div class="price">Q.@Html.DisplayFor(modelItem => item.TotalVendido)<span>@Html.DisplayFor(modelItem => item.FecEmision)</span></div>
                                            <div class="lines">
                                                <div>@Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre)</div>
                                                <div>@Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre)</div>
                                                <div>@Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre)</div>
                                            </div>
                                        </div>
                                    </a>
                                }
                                else if (item.CodEstado == 2)
                                {
                                    <a asp-action="Details" asp-route-id="@item.CodFactura">
                                        <div class="plan basic" onclick="void(0);" style="width: 100%;">
                                            <div class="title" style="background-color: #38ee00e5;"> @Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre) @Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerApellido)</div>
                                            <div class="price">Q.@Html.DisplayFor(modelItem => item.TotalVendido)<span>@Html.DisplayFor(modelItem => item.FecEmision)</span></div>
                                            <div class="lines">
                                                <a class="botones warning-border redondear" asp-action="Factura" asp-route-id="@item.CodFactura" style="margin:0px;"><span>Ver Factura</span></a>
                                            </div>
                                        </div>
                                    </a>
                                }
                                else if (item.CodEstado == 3)
                                {
                                    <a asp-action="Details" asp-route-id="@item.CodFactura">
                                        <div class="plan basic" onclick="void(0);" style="width: 100%;">
                                            <div class="title" style="background-color: #ee0000e5;"> @Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre) @Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerApellido)</div>
                                            <div class="price">Q.@Html.DisplayFor(modelItem => item.TotalVendido)<span>@Html.DisplayFor(modelItem => item.FecEmision)</span></div>
                                            <div class="lines">
                                                <div>@Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre)</div>
                                                <div>@Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre)</div>
                                                <div>@Html.DisplayFor(modelItem => item.CodClienteNavigation.PrimerNombre)</div>
                                            </div>
                                        </div>
                                    </a>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>

        <!-- Registrarse -->
        <div id="Pedidos Realizados">
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="text-center">
        @if (ViewBag.fech2 != null || ViewBag.fech2 != "" || ViewBag.fech1 != null || ViewBag.fech1 != "" || ViewBag.nombre != null || ViewBag.nombre != "")
        {
            @Html.PagedListPager((IPagedList)Model, page => Url.Action("TodosPedidos", new { page = page, Nombre = @ViewBag.nombre, FecFinal = @ViewBag.fech2, FecInici = @ViewBag.fech1 }))
        }
        else
        {
            @Html.PagedListPager((IPagedList)Model, page => Url.Action("TodosPedidos", new { page = page }))
        }
    </div>
</div>


@section Scripts {

    <script>
        $(document).ready(function () {
            $("form").each(function () { this.reset() });
        });
    </script>
    <script src="~/js/login.js"></script>
    <script src="~/js/pikaday.js"></script>
    <script src="~/js/pikarange.js"></script>
    <script>
        document.querySelectorAll('.pikarange').forEach(function (el) {
            var options = {
                numberOfMonths: 2,
                start: {
                    field: el.querySelector('input.pikarange-start'),
                    trigger: el.querySelector('button.pikarange-start')
                },
                end: {
                    field: el.querySelector('input.pikarange-end'),
                    trigger: el.querySelector('button.pikarange-end')
                },
                positionTarget: el,
                position: 'bottom center'
            };
            var optionAttr = el.getAttribute('data-options');
            if (optionAttr) {
                optionAttr = JSON.parse(optionAttr);
                for (var i in optionAttr) {
                    if (typeof optionAttr[i] === 'string' && optionAttr[i].match(/^[\d\-]+/)) {
                        options[i] = new Date(optionAttr[i]);
                    } else {
                        options[i] = optionAttr[i];
                    }
                }
            }
            var range = new Pikarange(options);
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}